### ISSUE TITLE
Antipop

### ISSUE THREAD

**Issue by Majkwin** [Kaijun/Acer-V5-573G-Hackintosh#13]
Hi
OS X puts internal sound card after some idle time to sleep. After powering it back on, a poping sound can be heard from speakers (especially with amp connected through line-out). Have You noticed it too? Did you manage to disable it?

**Comment by Kaijun** [comment]
won't fix 😄

**Comment by virusak** [comment]
It looks like it can be fixed by:
https://github.com/RehabMan/EAPD-Codec-Commander
