### ISSUE TITLE
10.10.2 screen tearing, no headphones output

### ISSUE THREAD

**Issue by a8vam** [Kaijun/Acer-V5-573G-Hackintosh#14]
I followed the guide to install 10.10.2 on my V573G (i5, 1920x1080) and most things work now besides:

- There's screen tearing, sometimes very severe when logging in, using Chrome, Launchpad, during video playback, etc. I did apply Majkwin's FakePCIID trick.

- Headphones output not working

Can you help me please?

**Comment by Kaijun** [comment]
Hello,

* you should probably change another ig-platform-id (in SDST/ or by using Clover)and figure out which matchs the best with your device...
* There's always bug with headphones... after plugging in the headphone, you should manually sleep/wake, otherwise it won't auto-switch sometimes...

**Comment by a8vam** [comment]
Thank you for replying so soon. The sleep/wake trick worked, now the headphones output works well.

I'm having a hard time finding another ig-platform-ids for HD 4400. Do you know where can I find those? Thanks again for helping.

**Comment by Kaijun** [comment]
@a8vam 
have a look at [this thread](http://www.insanelymac.com/forum/topic/291614-intel-hd4000-and-haswell-inject-aaplig-platform-id/?hl=%20haswell%20%20ig)

 yeah in the spoiler:

```
0 = 00000604
1 = 0000060c
2 = 00001604
3 = 0000160a
4 = 0000160c
5 = 00002604
6 = 0000260a
7 = 0000260c
8 = 0000260d
9 = 02001604
10 = 0300220d
11 = 0500260a
12 = 0600260a
13 = 0700260d
14 = 0800260a
15 = 08002e0a
```

for example my id is No.12, 
yeah it's also a little bit confusing with the format of ig-platform-id
in SSDT3: 0x06, 0x00, 0x26, 0x0a
in Clover: 0x0a260006

actually it is reversed... i think it would be better if you change both values in SSDT and Clover to ensure that the id is successfully injected.

A small tip: backup backup backup! DSDT/SSDT especially, just in case that you can't enter the system anymore and then you'll have no more chance to modify the DSDT/SSDT. I know it may be very annoying and tough to try all IDs out, but good luck. :four_leaf_clover:

**Comment by Kaijun** [comment]
tell me if it solves your problem, i'm also not 100% certain if it really works. 0600260a is an universal id which works for most people.

**Comment by a8vam** [comment]
Thanks a lot for helping! During experimenting with the ig-platform-ids the wireless went inactive and I can't seem to reactivate it. 

Yesterday it also happened but came back after a few restarts and some troubleshooting but I have no idea how. Has this happened to you?

Wired connection also won't work. :( It says it connects but can't even reach the router.

**Comment by Kaijun** [comment]
Yes sometimes it happens but I still haven't figured out what's the
problem...  My trick was: boot into Windows and toggle the wlan (on/off/on)
then reboot to osx... In most cases it works.  And this situation happens
really rarely.  I think it may be related to some intern activities of the
interaction between system and bios.  Yeah just guessing no idea...

**Comment by Kaijun** [comment]
Does the graphic card work properly now?

**Comment by a8vam** [comment]
Would be nice to boot back to Windows but it's gone now. I have it as a backup image on an external drive to put it back next to OS X though I don't have an idea yet how I could do that. Wireless came back somehow anyway.

I tried all 15 ideas and none worked. One of them even made the system unbootable, had to use a Ubuntu live disk.

Since the graphical lag is gone and there's only this tearing problem, maybe there's something else with OpenCL or Quartz? Don't know much about these though.

You don't have any tearing, right? Do you have the same configuration like me? V573G, i5, HD4400 + 750M, 1920x1080. Compared to the files Majkwin shared in the install instructions, do you know what you have differently? Thank you again for helping.

**Comment by a8vam** [comment]
It works now! Turned out the modified AppleIntelFramebufferAzul.kext was the culprit from Solution #8, replaced it with the original one and it's perfect now.

Do you know maybe how to put back the Windows 8.1 image to the other partition on the same drive?

Anyway, thank you for all the help!

**Comment by Kaijun** [comment]
Congrats.

Hmmm.. So you have your windows installed but couldn't boot from it? Have you ever made a backup for the Windows EFI partition? if yes then you should copy the `Microsoft` folder into `/EFI/`, same path with `Clover` folder. Then you'll see the Windows Option when you boot with Clover.

But if you haven't made any backup, I don't know if the `Microsoft` folder for booting is universal or not. you download it anywhere and have a try. if it doesn't work, i would suggest you to reinstall Windows.

But after reinstalling Windows, you should probably re-copy Clover into EFI and then add Clover into your boot list, see #7

**Comment by a8vam** [comment]
I don't have it anymore, just an empty partition for it and the backup image on an external drive created in Windows 8.1. Tried to boot from a Windows USB install drive and rebuild Windows from the image file but it wanted to delete every partition on the drive including OSX's.

**Comment by Kaijun** [comment]
@a8vam 

i don't know how you made your `backup image`, is that an image for the whole disk or just for a partition?  

i'm just not clear with the mechanism of restoring an image by Windows USB Installer. but if you have an empty partition, or even empty disk capacity, it should work.

so how does the partition layout look like now? could probably have a look at the `Disk Utility.app` in OSX?

**Comment by a8vam** [comment]
It's the system image backup functionality built into the system.

GUID partition table, one empty FAT32 partition reserved for Windows and the Mac OS Extended partition for OS X.

**Comment by Kaijun** [comment]
Hmm... it seems that all things look fine.

Then maybe it's the problem with build-in backup tool, it could probably backup the image with the partition schema.. so it works under the prerequisite that you will not change your partition layout and won't install something different...

you could probably try another approach to restore the image i think,  some magic tools in WinPE for example. i'm also not familiar with that.

it depends how important the datas in the backup is to you, if not then just reinstall Windows by using the Windows Installer, if you insist restoring the image, then backup all things you done to your OSX,

and i personally also have installed hundred times for doing such experimentation of Hackintosh, so take the trouble :smile:

**Comment by a8vam** [comment]
I'm still waiting with trying to reinstall Windows to have more free time for experimenting, meanwhile, do you know how to make the SD card reader work?

**Comment by Kaijun** [comment]
sorry i haven't done any researches of making the SD CardReader work...I even don't know that the laptop has such a thing...

**Comment by a8vam** [comment]
It's important for me to import my Photos from the SD card. I'm trying to find a solution and if I succeed maybe you can add it to the install guide later.

One thing that's bothering me is that the Preview and Quick view function sometimes work, sometimes not. They often show me no picture at all, just the empty background.

Tried the Solution in Issue 11 (https://github.com/Kaijun/Acer-V5-573G-Hackintosh/issues/11) but nothing changed. Do you have an idea what could be the problem? Thanks!

**Comment by Kaijun** [comment]
have you ever tried #9 [This Comment by Majkwin](https://github.com/Kaijun/Acer-V5-573G-Hackintosh/issues/9#issuecomment-71815507)? 
>With this mod we don't need to patch OpenCl anymore. Preview.app and everything else works just fine :)

**Comment by a8vam** [comment]
Yes I'm using this method. Maybe I just need to get an original libCLVMIGILPlugin.dylib, my bak version might also a patched one. Do you have an original one and could you please upload it for me?

**Comment by Kaijun** [comment]
https://mega.co.nz/#!xUx22K6A!t4U1ageTW1hjUkOVRuk9GhG-ZK7k5Ozz4hMjvmgyHfQ

i'm not sure if you also need run `sudo codesign -f -s - /System/Library/Frameworks/OpenCL.framework/Libraries/libCLVMIGILPlugin.dylib` after replacing this lib

**Comment by Majkwin** [comment]
No patching is required. Just restore original file
23 mar 2015 13:02 "Kaijun Chen" <notifications@github.com> napisał(a):

**Comment by a8vam** [comment]
Restoring original libCLVMIGILPlugin.dylib worked! Thank you!

**Comment by a8vam** [comment]
By the way, is it normal for suspending / restarting / shutting down to take like 10 seconds (on an SSD)?

**Comment by a8vam** [comment]
Do you know how to make the hdmi audio work?

**Comment by Kaijun** [comment]
@a8vam sry actually i have no hdmi audio device so i haven't tried... have a look at the tutorials and try yourself. :smile:

**Comment by a8vam** [comment]
@Kaijun Earlier you said: "There's always bug with headphones... after plugging in the headphone, you should manually sleep/wake, otherwise it won't auto-switch sometimes..."

I had the same experiences and your workaround worked well but now I've updated to 10.10.3, used Majkwin's solution in #15 for the no audio problem and the updated kext seems to work perfectly with auto-switching now, no need for the sleep/wake method anymore. :)

**Comment by Kaijun** [comment]
@a8vam Thanks for your information! I haven't updated 10.10.3 yet, as i said, i'm working on a project currently so i can't take any risks caused by updating... but i would really wanna a try after finishing my current project
