### ISSUE TITLE
Audio problem

### ISSUE THREAD

**Issue by Majkwin** [Kaijun/Acer-V5-573G-Hackintosh#15]
Hi!
I was forced to reinstall system and now I'm having problem with audio kext - I'm not able to enable audio output. I've installed all kexts and even changed in clover's Devices tab to inject Audio "0x03" device. What I'm doing wrong? This method was always working (sometimes after few tries), but now it isn't. Is there some new trick under 10.10.3?

To be clear - I'm using applehda and dummyhda kexts from @Kaijun repository here :)

**Comment by Majkwin** [comment]
Got it. Just update AppleHDA and DummyHDA. Apple changed something on 10.10.3.

http://www.insanelymac.com/forum/files/file/372-applehda-for-alc282/

**Comment by a8vam** [comment]
Following your instructions to install Yosemite 10.10.2 on the 573g, can you tell me how should I update it to 10.10.3, besides updating AppleHDA and DummyHDA?

**Comment by Majkwin** [comment]
Nothing else. There was problem only with audio

**Comment by a8vam** [comment]
So I can just update the system through the App Store and then update AppleHDA and DummyHDA and that's it?

**Comment by Majkwin** [comment]
Yes

**Comment by a8vam** [comment]
Thanks!

**Comment by Majkwin** [comment]
[DummyHDA.kext.zip](https://github.com/Kaijun/Acer-V5-573G-Hackintosh/files/192344/DummyHDA.kext.zip)
Attached updated DummyHDA.kext for 10.11.4 update. Just update it and everything will be working again :)

**Comment by Kaijun** [comment]
outdated 😄
