### ISSUE TITLE
100% Battery

### ISSUE THREAD

**Issue by wilsoxu** [Kaijun/Acer-V5-573G-Hackintosh#16]
Hi Kaijun,

Do you perhaps know the solution so that the battery percentage actually shows the real %? Mine stays stuck at 100% and I don't know how to fix it!

Thanks,
WilsoXU

**Comment by Kaijun** [comment]
@wilsoxu  I'm not sure what's the problem with your OSX, the battery percentage works without any problems in my machine. And no one else has reported this issue.  actually there is no extra fix for the battery, just installing the `ACPIBatteryManager.kext` is already enough.

**Comment by wilsoxu** [comment]
Hey @Kaijun , i managed to fix it with just wiping hard drive and reinstall Mac OS X and the Kexts again! Thanks for letting me know it works 100%

Also, I'm getting really slow boot times (takes about 2 minutes to boot into mac os x) because it gets stuck at the line:
"IOAPIC: Version 0x20 Vectors 64:103"  for about 1 minute. I've read on tonymac that it's something related to the DSDT i'm using? Do you know perhaps what vectors 64:103 means? Is it something to do with lines 64 to 103 in the DSDT? 

Furthermore, when my computer goes to sleep (closing lid or pressing Fn+F4), it 1 minute before it gets onto the lock screen and it is very laggy. Do you perhaps have this issue?
