### ISSUE TITLE
Slow Boot + Slow wake-up from sleep

### ISSUE THREAD

**Issue by wilsoxu** [Kaijun/Acer-V5-573G-Hackintosh#17]
I'm getting really slow boot times (takes about 2 minutes to boot into mac os x) because it gets stuck at the line:
"IOAPIC: Version 0x20 Vectors 64:103"  for about 1 minute. I've read on tonymac that it's something related to the DSDT i'm using? Do you know perhaps what vectors 64:103 means? Is it something to do with lines 64 to 103 in the DSDT? 

Furthermore, when my computer goes to sleep (closing lid or pressing Fn+F4), it 1 minute before it gets onto the lock screen and it is very laggy. Do you perhaps have this issue?

**Comment by Kaijun** [comment]
@wilsoxu Slow Boot Issue: What's your current Bios Version? My DSDT/SSDTs are only for the version 2.29. And what's your boot mode? UEFI or Legacy? I would highly recommend UEFI.

I'm still not really clear with your wake-up issue. What's the workflow?  Could you probably describe a little bit concretely?

**Comment by wilsoxu** [comment]
my bios version is 2.29 as well and i'm using UEFI boot mode :+1: so i'm not sure why it takes a long time to boot up. When i'm using my USB Mac Installer with the modified clover, I get this slow boot issue where it gets stuck at IOAPIC: Version 0x20 Vectors 64:103 for at least a minute

I think the wake-up issue may be related with the slow boot issue, something to do with the DSDT not being compatible with my specific laptop. 
Well, when I close the lid and then wake up my laptop after about an hour, it has a black screen for about a minute or more before I can any visuals (lock screen) and there are times when my trackpad doesn't work after wake or the laptop lags a lot until I restart it.

**Comment by Silveryard** [comment]
I can hell YouTube with slow Boot.
Look up your Device UUID in System Report 
Then Put a Key "SystemId" with your UUID in your chamaeleon Boot plist and restart. It should Boot much faster

**Comment by Kaijun** [comment]
@wilsoxu Yeah, you are right, `SB.PCI0.RP05.PEGP.ON / SB.PCI0.RP05.PEGP.OFF` is for toggling off the nvdia graphic card. 

But I'm also not sure if you still get some other problems if you continue using my DSDT/SSDTs, after all our models are not identical... I would rather write a guide of what i've done to my DSDT/SSDTs so that you all can modify the DSDT of your own model.

**Comment by wilsoxu** [comment]
@Silveryard it's the same amount of time to boot whether i change it or not sir!

@Kaijun that will be much appreciated actually! I made a pre-edited dsdt from magiasl but i don't know what to patch yet. my sleep with lid down doesn't work properly but sleeping by pressing the button currently works!
