### ISSUE TITLE
Audio Kext and Clover Settings under 10.9..5

### ISSUE THREAD

**Issue by masonwanglic** [Kaijun/Acer-V5-573G-Hackintosh#18]
Hi @Kaijun 
I am still using 10.9.5 under bios version 2.29. Here is my problem,
I am using everything provided from you, clover, kext etc. 
I installed AppleHDAIDT.kext and set clover as 0X001 and replaced
8408 ec10 -> 0000 0000
8508 ec10 -> 0000 0000
8419 d411 -> 8202 ec10
For this part, it has already been done in clover.
But rebuild and reboot, there is no sound...
I also tried 0x03 and there is still no luck

Can anyone please let me know how for bios 2.29 and 10.9.5?

**Comment by Kaijun** [comment]
Hi @masonwanglic 

as i mentioned (here)[https://github.com/Kaijun/Acer-V5-573G-Hackintosh/tree/master/Kexts/AppleHDA%20for%2010.9.3]

if you are using the new method (patching AppleHDA with Clover),  then you should notice:
  - Never install the patched AppleHDA.kext
  - if you are using my DSDT, then there is no need to set ' 0X001' or '0x03'
  - it's better to add `3d` for insurance, e.g. 3d 8408 ec10 -> 3d 0000 0000

**Comment by masonwanglic** [comment]
Thanks for the reminder. 
Now I have sound.
But slightly different from the read me, I installed the dummy kext instead of the AppleIDT kext.
then everything goes smoothly.
Thank you Kaijun!
