### ISSUE TITLE
473PG using your dsdt 

### ISSUE THREAD

**Issue by ezekiel1998** [Kaijun/Acer-V5-573G-Hackintosh#19]
My laptop V5-473PG using your dsdt , my spec i7-4500u gt750m hd4400 but I have some problem with sound card. my sound card is alc282 ,and I cant use it , no drivers =.=  how can I contact u ? QQ?

**Comment by ezekiel1998** [comment]
also i have the major problem is when i use it will suddenly lag and restart and i cant find the problem

**Comment by Kaijun** [comment]
@ezekiel1998 
- 声卡: 如果你是Yosemite 并且使用我的DSDT的话 请严格按照 [这个说明](https://github.com/Kaijun/Acer-V5-573G-Hackintosh/tree/master/Kexts/AppleHDA%20for%20Yosemite)
- 我不知道你说的 Lag是指哪方面的Lag... 还有重启 是什么情况下? 突发重启频率? 情况是否可再现?

我不常用QQ(上Github的频率都能比QQ高), 可以直接Github跟我讨论 或者给我发邮件 Demonbane点cn - Gmail

**Comment by Kaijun** [comment]
@ezekiel1998 
当然型号相差太大 DSDT直接用我的 可能会有不可预知的问题 最好附上你最原始的DSDT 我有空的话可以帮你改

**Comment by Kaijun** [comment]
Tutorial about how to patch DSDT/SSDTs: https://github.com/Kaijun/Acer-V5-573g-DSDT
