### ISSUE TITLE
Sleep not working

### ISSUE THREAD

**Issue by BliccZ** [Kaijun/Acer-V5-573G-Hackintosh#20]
Hello,
I am using your Clover config for my V5-573 (i5, GTX 850m, Bios 2.29). Almost everything is working fine but I have two small problems. 

1. I cannot go to sleep. When i press FN+F4 the display turns black and system seems to freeze. I have to power off the notebook to get it to work again. Closing the lid shows the same behavior. 

2. Boot takes extremely long. Same behavior as in Issue 17.

If I could at least get number 1 to work, OS X would be quite usable for me. Can someone maybe help me?

**Comment by Kaijun** [comment]
Hi,
I don't know if you have the same sleep problem as mine. As i described in
readme.md, it can't be woken up only if the laptop has run continuously for
several hours. Try sleeping directly after the laptop boots up before it
has run for hours. And see if it succeeds.

And the problem that the boot takes extreamly long, are you using UEFI plus
GPT?
But it could also be a reason that your specs are not exactly same as mine.
So the dsdt ssdts are not perfectly compatible.

**Comment by BliccZ** [comment]
Sleep also does not work when I try it just after booting. I have already tried UEFI boot as well as legacy boot. It is always the same. 

Maybe you could write I guide how you patched your DSDT/SSDT? Then I could get a compatible one.

**Comment by basharmadi** [comment]
@BliccZ Do you have native power management working? If you're using NullCPUPowerManagement Kext, sleep won't work. Plus, do you have QE/CI working? not having compatible graphics card will prevent the OS from sleeping

**Comment by Kaijun** [comment]
Tutorial about how to patch DSDT/SSDTs: https://github.com/Kaijun/Acer-V5-573g-DSDT
Sleep/Shutdown/Restart issue was fixed: check https://github.com/Kaijun/Acer-V5-573G-Hackintosh/tree/master/Management-Engine-Firmware
