### ISSUE TITLE
Turn off Touchscreen

### ISSUE THREAD

**Issue by Silveryard** [Kaijun/Acer-V5-573G-Hackintosh#22]
Is there a way to turn of the touchscreen? 
While working I use it a lot but I just can´t close my lid because it causes the Screen to spawn random inputs. This also wakes the device up when sleeping which is a bit annoying

**Comment by Majkwin** [comment]
573g had an option with touchscreen?

W dniu czwartek, 27 sierpnia 2015 Silveryard <notifications@github.com>
napisał(a):

> Is there a way to turn of the touchscreen?
> While working I use it a lot but I just can´t close my lid because it
> causes the Screen to spawn random inputs. This also wakes the device up
> when sleeping which is a bit annoying
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Kaijun/Acer-V5-573G-Hackintosh/issues/22>.
>


-- 
Pozdrawiam,
Michał Winiarski

**Comment by Silveryard** [comment]
The 573pg has one yes

**Comment by Silveryard** [comment]
Any Updates? @Kaijun

**Comment by Silveryard** [comment]
The touchscreen problem really is a bit of a dealbreaker. I do not use it that much as OS X is only partly designed for it. E.g. Drag & Drop works, but for scrolling on websites I need to scroll via scrollbars which are tiny in Safari.
So if its not possible to turn the touchscreen off on sleep maybe it is possible to turn it off completely? I cannot find anything

**Comment by Kaijun** [comment]
@Silveryard 
I only have 573G which has no touchscreen. You should probably google it how to turn it off...

**Comment by Silveryard** [comment]
Now turned off with my El Capitan Files
