### ISSUE TITLE
Not able to boot after updating from 10.10.1 to 10.10.5 ?

### ISSUE THREAD

**Issue by DroidArts** [Kaijun/Acer-V5-573G-Hackintosh#25]
I just installed Niresh Yosemite Zone 10.10.1 in my Acer aspire V5 573g and succeeded to start it. But when I update it to 10.10.5 from app store and after the installation process complete, It reboot and that's It. It not starting from boot screen. Please tell me how can I update it to 10.10.5 or suggest me any tutorial for that.

**Comment by Kaijun** [comment]
any logs?

**Comment by DroidArts** [comment]
There is showing one line but I am not able to read it nor able to record it with -v boot flag. is there any precautions I have to take before updating ?
On Nov 26, 2015 10:43 PM, Kaijun Chen <notifications@github.com> wrote:any logs?

**Comment by Kaijun** [comment]
you need to enable the KernelPM patch if you are using clover.

I would suggest using my Clover and making a **clean** OSX Installer. I'm not sure which bootloader or what kind of drivers is Niresh's version using.

**Comment by DroidArts** [comment]
Ok I will try clean installer using your clover, can you provide me step wise guide or any other info, because I am really newbie in this hackintosh stuff.

**Comment by Kaijun** [comment]
Have a look at the Tutorial written by @Majkwin #7

**Comment by Silveryard** [comment]
Yosemite Zone / Niresh versions should do fine. I am using it currently and I had not problems installing it with @Majkwin s Tutorial
