### ISSUE TITLE
BIOS 2.30

### ISSUE THREAD

**Issue by virusak** [Kaijun/Acer-V5-573G-Hackintosh#26]
Hi All,

Have you managed to try 2.30 BIOS?
http://global-download.acer.com/GDFiles/BIOS/BIOS/BIOS_Acer_2.30_A_A.zip?acerid=635573398499733760&Step1=ULTRA-THIN&Step2=ASPIRE&Step3=ASPIRE%20V5-573G&OS=ALL&LC=en&BC=ACER&SC=PA_6

**Comment by Silveryard** [comment]
I am currently running 2.30. BIOS related problems as far as I can tell

**Comment by Kaijun** [comment]
Check the new [Release 18.6.2016](https://github.com/Kaijun/Acer-V5-573G-Hackintosh/releases), It's totally new DSDT/SSDTs extracted from BIOS 2.30. 

Besides, i also wrote a tutorial how i process these files. [Check here](https://github.com/Kaijun/Acer-V5-573g-DSDT/).

It seems that all things work correctly as before. Shutdown issue after long time running still need to be tested. Don't know if the Intel ME solution mentioned here https://github.com/Kaijun/Acer-V5-573G-Hackintosh/issues/6#issuecomment-225346907 helps
