### ISSUE TITLE
HD audio in 10.11

### ISSUE THREAD

**Issue by michaelspeed** [Kaijun/Acer-V5-573G-Hackintosh#30]
i have been using Voodoo audio with 10.11. and i noticed the sound is very low. Does anyone has any idea how to fix that.?

**Comment by Silveryard** [comment]
I dont have any audio problems with 10.11. Maybe some settings in the Voodo Audio Settings panel are very low?

**Comment by michaelspeed** [comment]
ya got it. it was voodoo sound was low.
