### ISSUE TITLE
Nvidia 750m

### ISSUE THREAD

**Issue by michaelspeed** [Kaijun/Acer-V5-573G-Hackintosh#32]
anyone has got this working? i have installed the web driver it recognizes the card but shows 0mb cram

**Comment by Kaijun** [comment]
as i know, the graphical card can only be driven when the internal graphical card(HD4400) could be shut down.
 i don't know if currently the hackintosh community has figured out the solution, but it's really a historical problem and haven't been solved for a long time :smile:
