### ISSUE TITLE
unable to upgrade from 10.11.3 to 10.11.4

### ISSUE THREAD

**Issue by michaelspeed** [Kaijun/Acer-V5-573G-Hackintosh#33]
i get a memory alloc error while upgrading or even fresh install here are the screens
![img_20160325_095539_1](https://cloud.githubusercontent.com/assets/1447958/14038387/f2057d40-f275-11e5-9e17-28b02ba3ae22.jpg)
![Uploading IMG_20160325_095455.jpg…]()
first one while upgrading, second one is fresh install

**Comment by Silveryard** [comment]
Try to use OsxAptioFix2Drv.efi instead of OsxAptioFixDrv-64.efi
This might help

**Comment by michaelspeed** [comment]
done..thanx for the update.
