### ISSUE TITLE
ei caption install problem：osxAptioFixDrv

### ISSUE THREAD

**Issue by leehz** [Kaijun/Acer-V5-573G-Hackintosh#34]
osxAptioFixDrv: Starting overrides for System\Library\CoreServices\boot.efiUsing reloc block: no, hibernate wake: no++++++++++++++++++++++++++++++++++++++++++++++++ +++++ 

I have tried : 
The solutions for this problem are well known. OsxAptioFixDrv2-64.efi vs. OsxAptioFixDrv-64.efi (two versions 96mb/128mb [updated by me]). And disabling SIP config.plist/RtVariables/CrsActiveConfig=0x67.

Anyone has suffered this?

**Comment by leehz** [comment]
#21

**Comment by Skn0tt** [comment]
After updating, I have exactly the same issue as you. What exactly did you do to fix it?

**Comment by notly** [comment]
hello, add the right memory info in config.plist; 

follow the repo's config.plist

wish this will help.
