### ISSUE TITLE
Disable NVIDIA

### ISSUE THREAD

**Issue by michaelspeed** [Kaijun/Acer-V5-573G-Hackintosh#35]
can anyone help me to disable the nvidia graphics in the i7 branch?

**Comment by Kaijun** [comment]
i could probably 😄 
i saw you just modified the ssdt-5 section, which is not enough actually.
but i haven't touched the dsdt/ssdt stuffs for more than one yeah...
i should get familiar with it at first...

And youd ssdt/dsdt is sightly different from mine. 
what does the `X` in ssdt-*X mean? any difference with the one without X? how many ssdt do you have exactly?

**Comment by Kaijun** [comment]
and what have you done with SSDT-5?

**Comment by michaelspeed** [comment]
i used the intel brightness fix. or else my screen had so low brightness.
i uploaded the ssdt/dsdt as i got it. just the ssdt-5 is modiefied with the brightness fix

**Comment by Kaijun** [comment]
hi @michaelspeed 

I just wrote some of my experiences of modifying the DSDT/SSDTs from raw files.

please check: https://github.com/Kaijun/Acer-V5-573g-DSDT

you can also modify your owns and disable the graphic card. 

Tell me if it works!

**Comment by Kaijun** [comment]
hi @michaelspeed  still need help?

**Comment by michaelspeed** [comment]
ya i saw ur guide. but still cannot figure it out. DSDT is not my thing!!!

**Comment by michaelspeed** [comment]
one more thing out of topic. i installed 10.12 dp. works like a charm. although most of my applications are not compatible (primary little snitch) so had to revert back. if anyone needs the CLOVER config i can upload it.

**Comment by Kaijun** [comment]
@michaelspeed from which bios did you extract these DSDT/SSDT files?

**Comment by Kaijun** [comment]
I would highly recommend you to update the bios to 2.30 and update the Management Engine.

If your dsdt/ssdts are already from 2.30, then i would start straightly

**Comment by michaelspeed** [comment]
yes bios is 2.30 everything is updated. i couldn't get 10.10 running on older bios.

**Comment by michaelspeed** [comment]
but now i am on 10.11.5 with 2.30 and macos 10.12 looks promising

**Comment by Kaijun** [comment]
what's your cpu model?

**Comment by Kaijun** [comment]
![error-fixed](https://cloud.githubusercontent.com/assets/1693027/16306255/58a44026-395d-11e6-9e65-d3b7285edad5.png)
![patched](https://cloud.githubusercontent.com/assets/1693027/16306256/58aa5ee8-395d-11e6-966e-eb12cb559941.png)

rename to zip!
error-fixed is the files which i extracted from your raw dsdt/ssdts and fixed error. (If you want to patch yourself or do further research)
patched is the files you can use directly, I patched all fixes described in my tutorial. I removed the CPU part of your SSDTs, which are SSDT0-4. You can use [ssdtPRGen](https://github.com/Piker-Alpha/ssdtPRGen.sh) to generate your own SSDT for your CPU model.

If you don't know how to do it, let me know your CPU model!

**Comment by Kaijun** [comment]
@michaelspeed 
Here is the a simple guide about how to generate the SSDT of CPU: https://github.com/Kaijun/Acer-V5-573g-DSDT/blob/master/README.md#ssdt-generation

Let me know if all things work properly! 

I found your DSDT/SSDTs are just slightly different with mine. for example the order of the SSDTs. I don't know if they will have different impacts.

**Comment by michaelspeed** [comment]
thank so much trying it now

**Comment by Kaijun** [comment]
does it work? i gonna close this issue!

**Comment by michaelspeed** [comment]
sorry for late reply will try today. was out of station

**Comment by michaelspeed** [comment]
worked like a charm. thanx a lot. now no power consumption. will update my branch.
