### ISSUE TITLE
Crackling Sound After AppleHDA patch

### ISSUE THREAD

**Issue by michaelspeed** [Kaijun/Acer-V5-573G-Hackintosh#36]
i always hear loud crackling sound after i patched AppleHDA. is it me or there is a fix?

**Comment by Kaijun** [comment]
I don't have the problem you mentioned. all AppleHDA stuffs work as normal as in 10.10.

Which patch did you use?

I'm currently using this [magic AppleHDA patcher](http://www.insanelymac.com/forum/files/file/496-applehda-patcher/), and choose the ALC282v1.

It will also generate the dummyHDA, which could also patch on the fly through clover.

Test if it works.

I will upload my el captain configuration later.

**Comment by zwj0571** [comment]
@michaelspeed you can use my repo in github. it works well on my EI 10.11.5. basicly I use applealc.kext

**Comment by michaelspeed** [comment]
solved it. used the appleHDA patcher but later found out it already had the voodooHDA patch. so the sound was coming out odd
