### ISSUE TITLE
Not an issue, but a suggestion.

### ISSUE THREAD

**Issue by naorunaoru** [Kaijun/Acer-V5-573G-Hackintosh#39]
```xml
		<key>ig-platform-id</key>
		<string>0x0a260006</string>
```
You have this piece of code in your Clover's config. That didn't work well on my V5-573g (i5-4200U, HD4400, FullHD display).
I've dug into some specs and found that i5-4200U's HD4400 has GT2 core ([source](https://en.wikipedia.org/wiki/Haswell_(microarchitecture))), so the closest platform id is 0x0a16000c - Haswell ULT Mobile GT2 ([source](https://pikeralpha.wordpress.com/2014/08/28/appleintelframebufferazul-sh-v2-1-released/)). That worked perfectly with 4k@30fps over HDMI with no graphics corruption and kernel panics.

You can add this info to your README if you like. 

Oh and injecting ig-platform-id in SSDT didn't work at all.

**Comment by naorunaoru** [comment]
Another working ig-platform-id is 0x0a2e0008 - Haswell ULT E GT3.

**Comment by Kaijun** [comment]
I don't know what happened if you took 0x0a260006? Did the graphic still work with animations and effects? but only not compatible with 4k? or all things with graphic just don't work completely?

As i know, most HD4400/HD4600 devices are using 0x0a260006, i also tried some of other codes at the very beginning when i was hackintoshing this laptop, but only 0x0a260006 works... I can't remember if i have tried these two codes you mentioned.

And one more thing, i also injected the this codes into the SSDT-2, check the `_DSM` method under the `IGUP` device. Maybe Clover will override it with the code defined inside Clover.

**Comment by naorunaoru** [comment]
0x0a26006 caused my menubar to glitch out with funny colors and sometimes I had KPs with AppleIntelFramebuffer as a reason. 4k also did not work.

About SSDT-2 injection: I've tried injecting platform-id into SSDT-5 (that's where my IGPU lies) and it didn't show up properly in IORegistryExplorer.

**Comment by Kaijun** [comment]
which version of OSX r u running? 10.10?

**Comment by naorunaoru** [comment]
10.11.5 (15F34).

**Comment by Kaijun** [comment]
yes, i just came up with the issues submitted two years ago,  https://github.com/Kaijun/Acer-V5-573G-Hackintosh/issues/8#issuecomment-66925834
and https://github.com/Kaijun/Acer-V5-573G-Hackintosh/issues/14

They may have the same problem as yours. 

it seems that 0x0a260006 is not universal for all HD4400 devices, and i also have no idea if the id u mentioned is suitable for me. I would try later. If it is the best one indeed, i'll update the repo 😄

**Comment by Kaijun** [comment]
are u simply using my DSDT/SSDT or ur own files?

u said that IORegistryExplorer doesn't recognised your ig-platform-id. The reason could be wrong modification of DSDT/SSDTs.

**Comment by Kaijun** [comment]
If u r interested in modifying ur own DSDT/SSDTs, a brief tutorial could be found here: https://github.com/Kaijun/Acer-V5-573g-DSDT

**Comment by naorunaoru** [comment]
I'm using my own DSDT patched according to your guide.

**Comment by Kaijun** [comment]
Then injecting ig-platform-id through SSDT should have worked. No idea, but yeah, you can also keep staying with the clover configuration 😄

**Comment by naorunaoru** [comment]
Yeah, in the end it works so I don't see any reason to bother. :)

**Comment by virusak** [comment]
any ideas how convert this 0x0a16000c to such style 0x06, 0x00, 0x26, 0x0a, so we can insert iy to SSDT file ?

**Comment by Kaijun** [comment]
@virusak 
it's reversed with each Byte actually
0x0a260006 ->  0x06, 0x00, 0x26, 0x0A
so
0x0a16000c -> 0x0C, 0x00, 0x16, 0x0A
and
0x0a2e0008 -> 0x08, 0x00, 0x2e, 0x0A

**Comment by virusak** [comment]
@Kaijun Thank you!

**Comment by Kaijun** [comment]
i had tried 0x0a16000c for a while, seems good!
changed the ig-platform-id overall both in config.plist and SSDT
Thx again!
