### ISSUE TITLE
Current state of compatibility

### ISSUE THREAD

**Issue by Ace73** [Kaijun/Acer-V5-573G-Hackintosh#44]
Hey,

I feel it would be easier for new users to understand the state of events if we could all know where we stand on compatibility with Yosemite, El Capitan and Sierra, and how to get things working in each case.

Also, if an updated installation guide needs to be written, I'm available to do so.

**Comment by Kaijun** [comment]
Hmm..
for sure, all of us can fork this repo and write some instructions or guides and then send me a Pull Request. I would highly appreciate it!

However, after years of effort by all of us, we already have brief instruction for installation #7 which could basically cover all the troubles you would meet during the installation, we also have a [guide](https://github.com/Kaijun/Acer-V5-573g-DSDT) for DSDT modification, and all the compatibility issues of the new version could also be tracked in the discussion threads. 

Ye, it's probably not that clear, but all of us, who really wanna achieve a perfect hackintosh laptop, could always dig things out and find solution.

Besides, i don't think there would be new users, yeah, it has been 3 years after release of this laptop 😄

**Comment by Majkwin** [comment]
I'm not going to be that person anymore :D I won't update to Sierra and on Christmas I will finally buy a real Macbook.

**Comment by Kaijun** [comment]
@Majkwin haha, I would also buy one eventually 2 months later. Since I got a job in Shanghai and my company has kind of welfare policy for paying the costs if I bought a Mac 😁😁😁 but have to wait for another 2 months

**Comment by Ace73** [comment]
@Kaijun, you may be right. I'll close this issue.
