### ISSUE TITLE
Yosemite compatibility 

### ISSUE THREAD

**Issue by Majkwin** [Kaijun/Acer-V5-573G-Hackintosh#9]
Hi
I'll be glad to hear some opinions from using Yosemite on 573G. Is there any additional issues comparing Mavericks? What about Continuity function? Is it working and is bluetooth needed?

I'm gonna try it after official release, but maybe someone has beta alredy?

**Comment by geiszla** [comment]
I've just installed Yosemite 10.10.1, but when I'm trying to sing into the app store it says "Your device or computer could not be verified. Contact support for assistance."

I've already installed Realtek 8111 (1.2.3) kext, and the internet is fully working. Any ideas?

**Comment by geiszla** [comment]
OK, I got that one. Anybody whith the same problem:
1. Delete all network devices in System Preferences -> Network
2. Delete the file "/Library/Preferences/SystemConfiguration/NetworkInterfaces.plist"
3. Restart the system
4. Add the Ethernet device FIRST (at System Preferences -> Network)

**Comment by geiszla** [comment]
Also the touchpad seems a bit glitchy for me. The selection and drag and drop doesn't really work. Is there a way to solve this?

**Comment by Majkwin** [comment]
you have to change default system settings

Pozdrawiam,
Michał Winiarski

**Comment by Kaijun** [comment]
Yes the lag of double click is because of the default setting of the
Rehabman's Kext... You could probably modify the plist of the kext
Am 24.01.2015 20:40 schrieb "Geiszl András" <notifications@github.com>:

**Comment by geiszla** [comment]
Which option should I change? Cause I can`t find one related to double click or selection.

**Comment by Kaijun** [comment]
@geiszla 

it has been already about one yeah since i modified this shit. i'm not pretty sure: 

Open package:  

VoodooPS2Controller.kext/Contents/PlugIns/VoodooPS2Trackpad.kext/Contents/Info.plist

```
<key>DragExitDelayTime</key>
<integer>0</integer>
```

**Comment by geiszla** [comment]
Ok, now I had to reinstall the hackintosh because it couldn't boot (probably because I fore shut down when it couldn't came out of sleep). But now the touchpad doesn't work at all, not even under the main windows os. What could I possibly do wrong? The clover can affect the other oses, or did I messed up something in the bios? Pls help.

**Comment by Majkwin** [comment]
Has someone updated to 10.10.2 today? I have some serious graphical lags and I wonder if is it something unusual or maybe update damaged our hackintosh machine...

**Comment by Majkwin** [comment]
Already found a solution.
10.10.2 disables native hd4400 mobile support. In order to reenable internal graphics You need to:

1. Install (the newest) FakePCIID and FakePCIID_HD4600_HD4400
https://bitbucket.org/RehabMan/os-x-fake-pci-id/downloads

2. Change config.plist (you can do it via textedit app - just double click). 
!!! FIND AND REPLACE "intelGFX" and "ig-platform-id"

<key>FakeID</key>
		<dict>
			<key>ATI</key>
			<string>0x0</string>
			<key>IMEI</key>
			<string>0x0</string>
			<key>IntelGFX</key>
			<string>0x04128086</string>
			<key>LAN</key>
			<string>0x0</string>
			<key>NVidia</key>
			<string>0x0</string>
			<key>SATA</key>
			<string>0x0</string>
			<key>WIFI</key>
			<string>0x0</string>
			<key>XHCI</key>
			<string>0x0</string>
		</dict>




AND



<key>Graphics</key>
	<dict>
		<key>Inject</key>
		<dict>
			<key>ATI</key>
			<false/>
			<key>Intel</key>
			<true/>
			<key>NVidia</key>
			<false/>
		</dict>
		<key>ig-platform-id</key>
		<string>0x0a260006</string>
	</dict>

**Comment by Kaijun** [comment]
@Majkwin thanks a lot for your solution!!! it works like a charm now!!! you could also reference your comment in your own instruction :) good job :+1:

**Comment by Majkwin** [comment]
With this mod we don't need to patch OpenCl anymore. Preview.app and everything else works just fine :)

**Comment by Majkwin** [comment]
@Kaijun , if You have 10.10.2 and You didn't do anything with OpenCl patch, could you upload this file for me?

/System/Library/Frameworks/OpenCL.framework/Libraries/libCLVMIGILPlugin.dylib

**Comment by leehz** [comment]
thanks for the work!! dude,

**Comment by a8vam** [comment]
Hi, I managed to install Yosemite 10.10.2 and almost everything works and did Majkwin's FakePCIID trick to repair to graphics lag but now the screen's flickering a lot, do you know a way to fix this?

**Comment by striimer** [comment]
Trying compile own DSDT-SSDT's for V5-573G and can't figure out how to properly disable Nvidia. Tried cleanup and wak/pts paches from Rehabman repo, didn't work. Can you upload your Geoforce disable patches, for DSDT and SSDT. Thanks in advance.

**Comment by Kaijun** [comment]
@striimer 
i just assume that you already have basic knowledges of DSDT/SSDT, and you also have already cleaned up the DSDT/SSDT by using `iasl`:

-  add the declaration in `DSDT`:

```
External (_SB_.PCI0.RP05.PEGP._OFF, MethodObj)
External (_SB_.PCI0.RP05.PEGP._ON_, MethodObj)
```

- search for method `_PTS` and add ` \_SB.PCI0.RP05.PEGP._ON ()` at **begin** of the function
- search for method `_WAK` and add ` \_SB.PCI0.RP05.PEGP._OFF ()` at **end** of the function but **before**
```
        Return (Package (0x02)
        {
            Zero, 
            Zero
        })
```
- search for `_INI` in ` Scope (_SB.PCI0)`, and add ` \_SB.PCI0.RP05.PEGP._OFF ()` at **end** of the function

you can also have a look at my modified DSDT.dsl [here](https://github.com/Kaijun/Acer-V5-573G-Hackintosh/blob/master/DSDT/DSDT-For-BIOS-V2.29/DSDT.dsl) you could compare with yours.

**Comment by Kaijun** [comment]
@striimer 

but i would say just disabling Nvidia is still far away to make the whole DSDT/SSDT work... there are still lot of things to be done. if you are interested i could probably write a brief guide later, about how i deal with my DSDT/SSDT...

**Comment by striimer** [comment]
Thanks for the reply, i have very limited skills about patching, like simple disassembly and using ready txt type patches. Guide sounds good, as probably someone else V5-573g owner also may want have system optimizing to get out maximum performance. Yes, agree that there is many other patches to use correcting the raw disassembled tables. More-or-less survived with other things, power management, sound, graphic platform and so on (followed also your readme) , now stuck with brightness things, which not working correctly without Geoforce disable. By the way inspected your uploaded files, also Clover config. Seems you are using most common platform 0x0a260006, i have small glitches with it (1080p), i'm using 0x0a2e0008, which grants clean view with acceleration, without using additional patches, just Clover platform inject. Also using Clover id inject instead patching DSDT for ALC282, then you can more easy use different layout appleHDA versions without patching DSDT.

**Comment by Kaijun** [comment]
@striimer actually i'm always patching the DSDT/SSDT manually because Clover's patches are not really reliable sometimes... i haven't updated Clover for a long time so i don't know if it's becoming far more stable. 
i just name some points that we should modify:
- Power Management:  since we are using the KernelPM patch of Clover, so the power management works already problem-free, but a `proper SSDT` for speedstepping is necessary, and we should also patch a `Shutdown Patch` for fixing the shutdown problem
- Graphic: it's a relative huge project :smile: 
  * first of all, fix the compile error.
  * Disable Nvdia as i mentioned
  * add the ig-platform-id patch in SSDT-3.dsl (it's about the intergrated graphic card). of course you can also inject it by using Clover.
  * rename all GFX0 to IGPU in the **three SSDTs** by using the patch provided by Rehabman. (For making the speedstepping of GPU work)
  * in SSDT-3.dsl, which is about the integrated graphic card, apply the patch `fix Brightness Haswell` provided by Rehabman. (For making the Brightness work properly)
- Audio: As you said we can injecting the layout-id both in DSDT or Clover. and i also made a [patch kext](https://github.com/Kaijun/Acer-V5-573G-Hackintosh/tree/master/Kexts/AppleHDA%20for%20Yosemite)  for audio in order to making it possible to upgrade the audio kext on-the-fly.
- Others: 
  * fix USB3...or just use GenericUSBXHCI.kext easily...
  * custom keyboard shortcuts for adjusting the brightness.
  * some other small patches: e.g. Fix IRQ, Fix SBUS... I'm also not pretty sure if these are essential.

**Comment by striimer** [comment]
Thanks. I think i patched all those parches you mentioned. I believe my dsdt is already very close start Nvidia OFF, at least your PEG device containing ssdt works together with my dsdt (borrowed yours ssdt-1), Nviadia is disabled. But something missing in my own ssdt, when i'm using own, Nvidia not disabled. I zipped my modded dsl's, can you take look as expert. Long file names describing fixes which done, also with order number came from linux, not renamed yet as ssdt-1, ssdt-2 and so on.
As the site do not support zip upload here, i changed file extension to jpg, just reanme it back to zip.
![dsdt_ssdt](https://cloud.githubusercontent.com/assets/12103857/7329968/0f12be64-eaef-11e4-9990-f41c509d065f.jpg)

**Comment by Kaijun** [comment]
@striimer ok, would be better if you also provide your raw DSDT/SSDTs. and it's already a little bit late today, i would have a look at it tomorrow.

**Comment by striimer** [comment]
Thanks in advance. Attached native *.aml's from linux and iasl disassembled dsl's. Rename jpg to zip before unzipping. Let's comeback tomorrow. Have a nice sleep.
![tables](https://cloud.githubusercontent.com/assets/12103857/7330052/67d2ca2a-eaf0-11e4-94b1-995be3cbb685.jpg)

**Comment by striimer** [comment]
Forgot mention, running bios ver.2.30

**Comment by Kaijun** [comment]
@striimer what! 2.30 is already released? Thanks for your info... time to update the new bios and make a new DSDT :+1:

**Comment by Kaijun** [comment]
@striimer 'cause i just had a look at your DSDT but didn't find anything special... i also have no idea why it doesn't work. but i noticed that the order of your SSDTs are a little bit different with mine.  

Is it the original order? in my case, the SSDT of Geforce graphic card should be at first. but i'm also not pretty sure if it's the problem. or maybe something has been changed with the new 2.30 Bios.

I should have a look at the new 2.30 Bios when i have time.

**Comment by striimer** [comment]
Yes that's the original order of files i've got from linux. It's good if you gonna compile new patched tables, i can also try your version of ssdt's, as most of hardwares are same. Mostly DSDT may vary, few differences like wireless, i have BCM94352HMB, instead your 943228 chip and graphics. I have Geoforce GT750M, what's your Nvidia version ? did read from forums that V5-573G done even with GTX850M cards. Also when you compile new tables with bios 2.30, you'll see do you have same previous ssdt order or like i have.
Attached pci and usb devices list of my V5-573G. Just remove extension jpg, it's simple text file.
Waiting curiously your tables version. Wish success.
![v5_573g_devices](https://cloud.githubusercontent.com/assets/12103857/7392403/4a814dd6-ee90-11e4-9f79-7857d9a66df6.jpg)

**Comment by Silveryard** [comment]
Is there any new information abou BIOS 2.30 DSDT?
I had a running installation of Yosemite (First on HDD, then on SSD), but after sending it to repair, I got a new motherboard with the new BIOS version. 
Installation of OSX seem to work although I geht an Error when installation finishes.
BUT:
- I cannot change from legacy to UEFI (no boot devices detected)
- I only can boot to HDD from USB installed on Clover (Instant reboot when booting with HDD Clover)
- SSD OSX Installation doesn´t even show up in any situation
